# Site settings
title: Dominik Lenhardt
description: Systemarchitekt & DevOps Engineer – Hochverfügbare Cloud- und On-Prem-Infrastrukturen, Automatisierung, CI/CD & Cloud-Transformation
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "dominiklenhardt.de"

# User settings
username: Dominik Lenhardt
email: dominik@lenmail.de
twitter_username: OnkelDominik
github_username:  OnkelDom
linkedin_username: dominik-lenhardt-086645226
xing_username: Dominik_Lenhardt
stackoverflow_userid: 17848024
stackoverflow_username: dominik-lenhardt

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
